Drlife/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("base.urls")),
    path("auth/", include("userauths.urls")),
    path("patient/", include("patient.urls")),
    path("doctor/", include("doctor.urls")),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

base/urls.py
from django.urls import path
from base import views

app_name = "base"

urlpatterns = [
    path("", views.index, name="index"),
    path("service/<service_id>", views.service_detail, name="service_detail"),
    path("book-appointment/<service_id>/<doctor_id>/", views.book_appointment, name="book_appointment"),
    path("checkout/<billing_id>", views.checkout, name="checkout"),
    
    path("payment_status/<billing_id>/", views.payment_status, name="payment_status"),

    path("stripe_payment/<billing_id>/", views.stripe_payment, name="stripe_payment"),
    path("stripe_payment_verify/<billing_id>", views.stripe_payment_verify, name="stripe_payment_verify"),

    path("paypal_payment_verify/<billing_id>/", views.paypal_payment_verify, name="paypal_payment_verify"),

    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("privacy-policy/", views.privacy_policy, name="privacy_policy"),
    path("terms-conditions/", views.terms_conditions, name="terms_conditions"),
    path("services/", views.services, name="services"),
]

patient/urls.py
from django.urls import path
from patient import views

app_name = "patient"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("appointment/", views.appointment, name="appointment"),
    path("appointment/<int:appointment_id>", views.appointment_detail, name="appointment_detail"),

    path("cancel_appointment/<int:appointment_id>", views.cancel_appointment, name="cancel_appointment"),
    path("activate_appointment/<int:appointment_id>", views.activate_appointment, name="activate_appointment"),

    path("medical_report/<int:appointment_id>", views.medical_report, name="medical_report"),

    path("payments/", views.payments, name="payments"),
    path("notifications/", views.notifications, name="notifications"),
    path("seen_notification/<int:id>", views.seen_notification, name="seen_notification"),

    path("profile/", views.profile, name="profile"),

    path("prescription/<int:appointment_id>", views.prescription, name="prescription"),
    path("medical_report/<int:appointment_id>", views.medical_report, name="medical_report"),
]

userauths/urls.py
from django.urls import path

from userauths import views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.register_view , name="sign-up"),
    path("sign-in/", views.login_view , name="sign-in"),
    path("sign-out/", views.logout_view , name="sign-out"),
    path("forgot-password/", views.forgot_password_view , name="forgot-password"),
    path("reset-password/<str:uidb64>/<str:token>/", views.reset_password_view, name="reset-password"),
]

patient/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from userauths import models as userauths_models

NOTIFICATION_TYPE = (
    ("Appointment Scheduled","Appointment Scheduled"),
    ("Appointment Cancelled","Appointment Cancelled"),
)

GENDER_CHOICES = (
    ('Male', 'Male'),
    ('Female', 'Female'),
)

# Create your models here.
class Patient(models.Model):
    user = models.OneToOneField(userauths_models.User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="images", null=True, blank=True)
    mobile = models.CharField(max_length=15, null=True, blank=True,)
    email = models.EmailField(max_length=100)
    address = models.CharField(max_length=100, null=True, blank=True)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES)
    dob = models.DateField()

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"
    
    def age(self):
        today = timezone.now().date()
        return today.year - self.dob.year - ((today.month, today.day) < (self.dob.month, self.dob.day))


class Notification(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.SET_NULL, null=True, blank=True)
    appointment = models.ForeignKey("base.Appointment", on_delete=models.CASCADE, null=True, blank=True , related_name="patient_appointment_notification")
    type = models.CharField(max_length=100, choices=None)
    seen = models.BooleanField(default=False)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Notification"

    def __str__(self):
        return f"{self.patient.user.first_name} {self.patient.user.last_name} Notification"

patient/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.db import models
from django.contrib import messages

from patient import models as patient_models
from base import models as base_models
import patient


# Create your views here.
@login_required
def dashboard(request):
    patient = patient_models.Patient.objects.get(user=request.user)
    appointments = base_models.Appointment.objects.filter(patient=patient)
    notifications = patient_models.Notification.objects.filter(patient=patient)
    total_spent = base_models.Billing.objects.filter(patient=patient).aggregate(total_spent=models.Sum("total"))["total_spent"]

    context = {
        "patient": patient,
        "appointments": appointments,
        "notifications": notifications,
        "total_spent": total_spent,
    }

    return render(request, "patient/dashboard.html", context)

@login_required
def appointment(request):
    patient = patient_models.Patient.objects.get(user=request.user)
    appointments = base_models.Appointment.objects.filter(patient=patient)

    context= {
        "appointments": appointments,
    }    

    return render(request, "patient/appointment.html", context)

@login_required
def appointment_detail(request, appointment_id):
    patient = patient_models.Patient.objects.get(user=request.user)
    appointment = base_models.Appointment.objects.get(id=appointment_id, patient=patient)

    medical_records = base_models.MedicalRecord.objects.filter(appointment=appointment)
    lab_tests = base_models.LabTest.objects.filter(appointment=appointment)
    prescriptions = base_models.Prescription.objects.filter(appointment=appointment)    

    context = {
        "appointment": appointment,
        "medical_records": medical_records,
        "lab_tests": lab_tests,
        "prescriptions": prescriptions,
    }
    return render(request, "patient/appointment_detail.html", context)

@login_required
def cancel_appointment(request, appointment_id):
    patient = patient_models.Patient.objects.get(user=request.user)
    appointment = base_models.Appointment.objects.get(id=appointment_id, patient=patient)
    appointment.status = "Cancelled"
    appointment.save()

    messages.success(request, "Appointment cancelled successfully.")
    return redirect("patient:appointment", appointment_id=appointment_id)

def activate_appointment(request, appointment_id):
    patient = patient_models.Patient.objects.get(user=request.user)
    appointment = base_models.Appointment.objects.get(id=appointment_id, patient=patient)
    appointment.status = "Scheduled"
    appointment.save()

    messages.success(request, "Appointment Re-Scheduled successfully.")
    return redirect("patient:appointment", appointment_id=appointment_id)


@login_required
def medical_report(request, appointment_id):
    patient = patient_models.Patient.objects.get(user=request.user)
    appointment = base_models.Appointment.objects.get(id=appointment_id, patient=patient)
    medical_records = base_models.MedicalRecord.objects.filter(appointment=appointment)

    context = {
        "appointment": appointment,
        "medical_records": medical_records,
    }
    return render(request, "patient/medical_report.html", context)

@login_required
def payments(request):
    patient = patient_models.Patient.objects.get(user=request.user)
    payments = base_models.Billing.objects.filter(patient=patient, status="Paid")

    context = { 
        "payments": payments,
    }
    return render(request, "patient/payments.html", context)

@login_required
def notifications(request):
    patient = patient_models.Patient.objects.get(user=request.user)
    notifications = patient_models.Notification.objects.filter(patient=patient)

    context = {
        "notifications": notifications,
    }
    return render(request, "patient/notifications.html", context)

@login_required
def seen_notification(request, id):
    patient = patient_models.models.Patient.objects.get(user=request.user)
    notification = patient_models.models.Notification.objects.get(patient=patient, id=id)
    notification.seen = True
    notification.save()

    messages.success(request, "Notification Seen.")
    return redirect("patient:notifications")


@login_required
def profile(request):
    patient = patient_models.Patient.objects.get(user=request.user)
    formatted_dob = patient.dob.strftime("%Y-%m-%d")
    
    if request.method == "POST":
        first_name = request.POST.get("first_name")
        last_name = request.POST.get("last_name")
        image = request.FILES.get("image")
        mobile = request.POST.get("mobile")
        address = request.POST.get("address")
        dob = request.POST.get("dob")

        if image:
            patient.image = image
        
        patient.user.first_name = first_name
        patient.user.last_name = last_name
        patient.user.save()
        
        patient.mobile = mobile
        patient.address = address
        patient.dob = dob
        patient.save()

        messages.success(request, "Profile Updated Successfully.")
        return redirect("patient:profile")
    
    context = {
        "patient": patient,
        "formatted_dob": formatted_dob,
    }
    return render(request, "patient/profile.html", context)


@login_required
def prescription(request, appointment_id):
    appointment = base_models.Appointment.objects.get(appointment_id=appointment_id)
    prescriptions = base_models.Prescription.objects.filter(appointment=appointment)

    context = {
        "appointment": appointment,
        "prescriptions": prescriptions,
    }
    return render(request, "patient/prescription.html", context)

@login_required
def medical_report(request, appointment_id):
    appointment = base_models.Appointment.objects.get(appointment_id=appointment_id)
    medical_records = base_models.MedicalRecord.objects.filter(appointment=appointment)

    context = {
        "appointment": appointment,
        "medical_records": medical_records,
    }
    return render(request, "patient/medical_report.html", context)

templates/patient/appointment.html
{% extends 'partials/base.html' %}
{% block content %}
<section class="pt-5 pb-5">
    <div class="container">
        <div class="row mt-0 mt-md-4">
            
            {% include 'patient/sidebar.html' %}

            <div class="col-lg-9 col-md-8 col-12">
                <h4 class="mb-0 mb-4 fw-bold">Appointment</h4>
                <div class="card mb-4">
                    <!-- Single item -->
                    {% for a in appointments %}
                    <div class="shadow border p-3 mb-4 rounded-4">
                        <p>
                            <a class="" data-bs-toggle="collapse" href="#collapseExample{{a.appointment_id}}" role="button" aria-expanded="false" aria-controls="collapseExample">
                                <p><span class="fw-semibold text-dark">Appointment ID:</span> {{a.appointment_id}}</p>
                                <p><span class="fw-semibold text-dark">Que Number:</span> {{a.que_number}}</p>
                                <p><span class="fw-semibold text-dark">Doctor:</span> {{a.doctor.user.first_name}} {{a.doctor.user.last_name}} </p>
                                <p><span class="fw-semibold text-dark">Issue:</span> {{a.issues}}</p>
                                <p><span class="fw-semibold text-dark">Date:</span> {{a.appointment_date|date:"d/m/Y"}}</p>
                            </a>
                            <a class="btn btn-primary btn-sm" data-bs-toggle="collapse" href="#collapseExample{{a.appointment_id}}" role="button" aria-expanded="false" aria-controls="collapseExample"> Show more <i class="fas fa-arrow-down ms-2"></i> </a>
                        </p>
                        <div class="collapse" id="collapseExample{{a.appointment_id}}">
                            <div>
                                <p><span class="fw-semibold text-dark">Status:</span> {{a.status}}</p>
                                <p>
                                    <span class="fw-semibold text-dark">Action:</span> <a href="{% url 'patient:cancel_appointment' a.appointment_id %}" class="btn btn-outline-danger btn-sm">Cancel Appointment <i class="fas fa-trash ms-2"></i></a>
                                </p>
                                <p class="border-top pt-4"></p>
                                <p>
                                     <a href="{% url 'patient:medical_report' a.appointment_id %}" class="btn btn-secondary btn-sm">View Medical Reports<i class="fas fa-arrow-right ms-2"></i></a>
                                </p>
                                <p>
                                     <a href="{% url 'patient:prescription' a.appointment_id %}" class="btn btn-secondary btn-sm">View Prescription<i class="fas fa-arrow-right ms-2"></i></a>
                                </p>
                            </div>
                        </div>
                    </div>
                    {% endfor %}

                </div>
            </div>
        </div>
    </div>
</section>


{% endblock content %}

templates/patient/appointment_detail.html
{% extends 'partials/base.html' %}
{% block content %}
    <section class="pt-5 pb-5">
        <div class="container">
            <div class="row mt-0 mt-md-4">
                <!-- Sidebar Placeholder -->
                <div class="col-lg-3 col-md-4 col-12">
                    <!-- Include Sidebar Content Here -->
                    {% include "patient/sidebar.html" %}
                </div>

                <div class="col-lg-9 col-md-8 col-12">
                    <h4 class="mb-0 mb-4 fw-bold">Appointment Detail #12345</h4>
                    <div class="card mb-4">
                        <div class="shadow border p-3 mb-4 rounded-4">
                            <p>
                                <a>
                                    <p><span class="fw-semibold text-dark">Appointment ID:</span> #12345</p>
                                    <p><span class="fw-semibold text-dark">Service:</span> General Checkup</p>
                                    <p><span class="fw-semibold text-dark">Doctor:</span> Dr. John Doe</p>
                                    <p><span class="fw-semibold text-dark">Issue:</span> Headache</p>
                                    <p><span class="fw-semibold text-dark">Symptoms:</span> Nausea, Dizziness</p>
                                    <p><span class="fw-semibold text-dark">Status:</span> Scheduled</p>
                                    <p><span class="fw-semibold text-dark">Date:</span> 2024-08-16</p>
                                    <p>
                                        <span class="fw-semibold text-dark">Action:</span>

                                        <a href="#" class="btn btn-outline-danger btn-sm">Cancel Appointment <i class="fas fa-trash ms-2"></i></a>
                                        <a href="#" class="btn btn-outline-success btn-sm">Complete Appointment <i class="fas fa-check-circle ms-2"></i></a>
                                    </p>
                                </a>
                            </p>
                        </div>
                    </div>

                    <h4 class="mb-0 mb-4 fw-bold">Medical Reports</h4>
                    <div class="card mb-4">
                        <div class="border p-3 mb-4 rounded-4">
                            <div class="shadow p-3 rounded-4 mb-3">
                                <p><span class="fw-semibold text-dark">Diagnosis:</span> Migraine</p>
                                <p><span class="fw-semibold text-dark">Treatment:</span> Pain relievers, Rest</p>
                            </div>
                            <p>No medical records</p>
                        </div>
                    </div>

                    <h4 class="mb-0 mb-4 fw-bold">Labs Tests Reports</h4>
                    <div class="card mb-4">
                        <div class="border p-3 mb-4 rounded-4">
                            <div class="shadow p-3 rounded-4 mb-3">
                                <p><span class="fw-semibold text-dark">Test Name:</span> Blood Test</p>
                                <p><span class="fw-semibold text-dark">Description:</span> Complete Blood Count</p>
                                <p><span class="fw-semibold text-dark">Result:</span> Normal</p>
                            </div>
                            <p>No lab tests</p>
                        </div>
                    </div>

                    <h4 class="mb-0 mb-4 fw-bold">Prescription</h4>
                    <div class="card mb-4">
                        <div class="border p-3 mb-4 rounded-4">
                            <div class="shadow p-3 rounded-4 mb-3">
                                <p><span class="fw-semibold text-dark">Medications:</span> Ibuprofen 400mg, 3 times a day</p>
                            </div>
                            <p>No prescriptions</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


{% endblock content %}

templates/patient/dashboard.html
{% extends 'partials/base.html' %}


{% block content %}

        <section class="pt-5 pb-5">
            <div class="container">
                <div class="row mt-0 mt-md-4">
                
                    {% include 'patient/sidebar.html' %}

                    <div class="col-lg-9 col-md-8 col-12">
                        <div class="row mb-4">
                            <h4 class="mb-0 mb-4 fw-bold">Dashboard</h4>
                            <div class="col-sm-6 col-lg-4 mb-3 mb-lg-0">
                                <div class="d-flex justify-content-center align-items-center p-4 bg-danger bg-opacity-10 rounded-3">
                                    <span class="display-6 lh-1 text-purple mb-0">
                                        <i class="fas fa-calendar text-danger"></i>
                                    </span>
                                    <div class="ms-4">
                                        <div class="d-flex">
                                            <h5 class="mb-0 fw-bold">{{appointments.count}}</h5>
                                        </div>
                                        <p class="mb-0 h6 fw-semibold">Appointments</p>
                                    </div>
                                </div>
                            </div>

                            <div class="col-sm-6 col-lg-4 mb-3 mb-lg-0">
                                <div class="d-flex justify-content-center align-items-center p-4 bg-dark bg-opacity-10 rounded-3">
                                    <span class="display-6 lh-1 text-dark mb-0">
                                        <i class="fas fa-bell"></i>
                                    </span>
                                    <div class="ms-4">
                                        <div class="d-flex">
                                            <h5 class="mb-0 fw-bold">{{notifications.count}}</h5>
                                        </div>
                                        <p class="mb-0 h6 fw-semibold">Notifications</p>
                                    </div>
                                </div>
                            </div>

                            <div class="col-sm-6 col-lg-4 mb-3 mb-lg-0">
                                <div class="d-flex justify-content-center align-items-center p-4 bg-success bg-opacity-10 rounded-3">
                                    <span class="display-6 lh-1 text-success mb-0">
                                        <i class="fas fa-medal"></i>
                                    </span>
                                    <div class="ms-4">
                                        <div class="d-flex">
                                            <h5 class="mb-0 fw-bold">{{ total_spent }}MAD</h5>
                                        </div>
                                        <p class="mb-0 h6 fw-semibold">Amount Spent</p>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="card mb-4 mt-5">
                            <div class="table-responsive overflow-y-hidden">
                                <table class="table mb-0 text-nowrap table-hover table-centered text-nowrap">
                                    <thead class="table-light">
                                        <tr>
                                            <th>Appointment ID</th>
                                            <th>Que Number</th>
                                            <th>Doctor</th>
                                            <th>Issue</th>
                                            <th>Date</th>
                                            <th>Payment Status</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                       {% for a in appointments %}
                                       <tr>
                                            <td>{{ a.appointment_id }}</td>
                                            <td>{{ a.que_number }}</td>
                                            <td>{{ a.doctor.user.first_name }} {{a.doctor.user.last_name}} </td>
                                            <td>{{ a.issues }}</td>
                                            <td>{{ a.appointment_date|date:"d/m/Y" }}</td>
                                            <td>{{ a.status }}</td>
                                            <td>
                                                <a href="" class="btn btn-danger btn-sm rounded-pill" >Cancel Appointment <i class="fas fa-trash ms-2"></i></a>
                                            </td>
                                        </tr>
                                       {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

{% endblock content %}
    

templates/patient/medical_report.html
{% extends 'partials/base.html' %}
{% block content %}

    <section class="pt-5 pb-5">
        <div class="container">
            <div class="row mt-0 mt-md-4">
                {% include 'patient/sidebar.html' %}
                <div class="col-lg-9 col-md-8 col-12">
                    <h4 class="mb-0 mb-4 fw-bold">Medical Reports</h4>
                    <div class="card mb-4 mt-2">
                        {% if medical_records %}
                        {% for mr in medical_records %}
                        <div class="shadow border p-3 mb-4 rounded-4">
                            <p>
                                <a class="" data-bs-toggle="collapse" href="#collapseExample{{mr.id}}" role="button" aria-expanded="false" aria-controls="collapseExample">
                                    <p><span class="fw-semibold text-dark">Record ID:</span> {{mr.id}}</p>
                                    <p><span class="fw-semibold text-dark">Doctor:</span> {{mr.doctor.user.first_name}} {{mr.doctor.user.last_name}}</p>
                                    <p><span class="fw-semibold text-dark">Record Date:</span> {{mr.record_date|date:"d/m/Y"}}</p>
                                </a>
                                <a class="btn btn-primary btn-sm" data-bs-toggle="collapse" href="#collapseExample{{mr.id}}" role="button" aria-expanded="false" aria-controls="collapseExample"> Show more <i class="fas fa-arrow-down ms-2"></i> </a>
                            </p>
                            <div class="collapse" id="collapseExample{{mr.id}}">
                                <div>
                                    <p><span class="fw-semibold text-dark">Diagonises:</span> {{mr.diagnosis}}</p>
                                    <p><span class="fw-semibold text-dark">Prescription:</span> {{mr.prescription}}</p>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        {% else %}
                        <p>No Medical Records Found.</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock content %}

templates/patient/notifications.html
{% extends 'partials/base.html' %}
{% block content %}

<section class="pt-5 pb-5">
    <div class="container">
        <div class="row mt-0 mt-md-4">
            
            {% include 'patient/sidebar.html' %}

            <div class="col-lg-9 col-md-8 col-12">
                <h4 class="mb-0 mb-4 fw-bold">Notifications</h4>
                <ul class="list-group list-group-flush">
                    {% for n in notifications %}
                    <li class="list-group-item p-2 shadow rounded-3 mb-3">
                        <div class="d-flex">
                            <div class="ms-3 mt-2">
                                <div class="d-flex align-items-center justify-content-between">
                                    <div>
                                        <p class="mb-0 fs-5">{{ n.title }}</p>
                                    </div>
                                </div>
                                <div class="mt-2">
                                    <p class="mt-1">
                                        <span class="me-2 fw-bold"> Date: <span class="fw-light"> {{ n.date }}</span> </span>
                                    </p>
                                    <p>
                                        <button class="btn btn-outline-secondary btn-sm" type="button">Mark as Seen <i class="fas fa-inbox ms-2"></i></button>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </li>
                    {% empty %}
                    <li class="list-group-item p-2 shadow rounded-3 mb-3">
                        <div class="d-flex">
                            <div class="ms-3 mt-2">
                                <div class="d-flex align-items-center justify-content-between">
                                    <div>
                                        <p class="mb-0 fs-5">No Notifications</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</section>


{% endblock content %}

templates/patient/prescription.html
{% extends 'partials/base.html' %}
{% block content %}

{% endblock content %}

templates/patient/sidebar.html
{% load static %}
<div class="col-lg-3 col-md-4 col-12">
    <nav class="navbar navbar-expand-md shadow mb-4 mb-lg-0 sidenav border rounded-4">
        <a class="d-xl-none d-lg-none d-md-none text-inherit fw-bold text-decoration-none text-dark p-3" href="#"> Menu </a>
        <button class="navbar-toggler d-md-none icon-shape icon-sm rounded bg-primary text-light m-3" type="button" data-bs-toggle="collapse" data-bs-target="#sidenav" aria-controls="sidenav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="bi bi-grid"></span>
        </button>

        <div class="collapse navbar-collapse p-3" id="sidenav">
            <div class="navbar-nav flex-column">
                <div class="d-flex align-items-center mb-3">
                    <img src="{% if request.user.patient.image %}{{request.user.patient.image.url}}{% else %}{% static 'media/photos/default.jpg' %}{% endif %}" alt="avatar" class="rounded-circle avatar-xl" style="width: 70px; height: 70px; object-fit: cover" />
                    <div class="ms-3">
                        <h5 class="mb-0 fw-bold">{{ request.user.patient.user.first_name }} {{ request.user.patient.user.last_name }}</h5>
                        <p class="mb-1 fs-6">Patient ID: # {{ request.user.patient.id }}</p>
                    </div>
                </div>
                <ul class="list-unstyled ms-n2 mb-4">
                    <li class="nav-item">
                        <a class="dropdown-item nav-link" href="{% url 'patient:dashboard' %}"><i class="bi bi-grid-fill"></i> Dashboard</a>
                    </li>
                    <li class="nav-item">
                        <a class="dropdown-item nav-link" href="{% url 'patient:appointment' %}"><i class="fas fa-calendar"></i> Appointment</a>
                    </li>
                    <li class="nav-item">
                        <a class="dropdown-item nav-link" href="/patient/medical-reports.html"><i class="fas fa-notes-medical"></i> Medical Reports</a>
                    </li>
                    <li class="nav-item">
                        <a class="dropdown-item nav-link" href="/patient/prescription.html"><i class="fas fa-pills"></i> Prescription</a>
                    </li>
                    <li class="nav-item">
                        <a class="dropdown-item nav-link" href="{% url 'patient:payments' %}"><i class="fas fa-credit-card"></i> Billing</a>
                    </li>
                    <li class="nav-item">
                        <a class="dropdown-item nav-link" href="{% url 'patient:notifications' %}"><i class="fas fa-bell"></i> Notifications</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'patient:profile' %}"> <i class="fas fa-edit"></i> Edit Profile </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'userauths:sign-out' %}"> <i class="fas fa-sign-out-alt"></i> Sign Out </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</div>