Drlife/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("base.urls")),
    path("auth/", include("userauths.urls")),
    path("patient/", include("patient.urls")),
    path("doctor/", include("doctor.urls")),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

base/urls.py
from django.urls import path
from base import views

app_name = "base"

urlpatterns = [
    path("", views.index, name="index"),
    path("service/<service_id>", views.service_detail, name="service_detail"),
    path("book-appointment/<service_id>/<doctor_id>/", views.book_appointment, name="book_appointment"),
    path("checkout/<billing_id>", views.checkout, name="checkout"),
    
    path("payment_status/<billing_id>/", views.payment_status, name="payment_status"),

    path("stripe_payment/<billing_id>/", views.stripe_payment, name="stripe_payment"),
    path("stripe_payment_verify/<billing_id>", views.stripe_payment_verify, name="stripe_payment_verify"),

    path("paypal_payment_verify/<billing_id>/", views.paypal_payment_verify, name="paypal_payment_verify"),

    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("privacy-policy/", views.privacy_policy, name="privacy_policy"),
    path("terms-conditions/", views.terms_conditions, name="terms_conditions"),
    path("services/", views.services, name="services"),
]

doctor/urls.py
from  django.urls import path
from doctor import views

app_name = 'doctor'

urlpatterns = [
    path("", views.dashboard, name='dashboard'),
    path("appointments/", views.appointments, name='appointments'),
    path("appointments/<appointment_id>/", views.appointment_detail, name='appointment_detail'),

    path("cancel_appointment/<appointment_id>/", views.cancel_appointment, name="cancel_appointment"),
    path("activate_appointment/<appointment_id>/", views.activate_appointment, name="activate_appointment"),
    path("complete_appointment/<appointment_id>/", views.complete_appointment, name="complete_appointment"),

    path("add_medical_report/<appointment_id>/", views.add_medical_report, name="add_medical_report"),
    path("edit_medical_report/<appointment_id>/<medical_report_id>/", views.edit_medical_report, name="edit_medical_report"),

    path("add_lab_test/<appointment_id>/", views.add_lab_test, name="add_lab_test"),
    path("edit_lab_test/<appointment_id>/<lab_test_id>/", views.edit_lab_test, name="edit_lab_test"),

    path("add_prescription/<appointment_id>/", views.add_prescription, name="add_prescription"),
    path("edit_prescription/<appointment_id>/<prescription_id>/", views.edit_prescription, name="edit_prescription"),

    path("payments/", views.payments, name="payments"),

    path("notifications/", views.notifications, name="notifications"),
    path("seen_notification/<id>/", views.seen_notification, name="seen_notification"),

    path("profile/", views.profile, name="profile"),

]

patient/urls.py
from django.urls import path
from patient import views

app_name = "patient"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("appointment/", views.appointment, name="appointment"),
    path("appointment/<int:appointment_id>", views.appointment_detail, name="appointment_detail"),

    path("cancel_appointment/<int:appointment_id>", views.cancel_appointment, name="cancel_appointment"),
    path("activate_appointment/<int:appointment_id>", views.activate_appointment, name="activate_appointment"),

    path("medical_report/<int:appointment_id>", views.medical_report, name="medical_report"),

    path("payments/", views.payments, name="payments"),
    path("notifications/", views.notifications, name="notifications"),
    path("seen_notification/<int:id>", views.seen_notification, name="seen_notification"),

    path("profile/", views.profile, name="profile"),

    path("prescription/<int:appointment_id>", views.prescription, name="prescription"),
    path("medical_report/<int:appointment_id>", views.medical_report, name="medical_report"),
]

userauths/urls.py
from django.urls import path

from userauths import views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.register_view , name="sign-up"),
    path("sign-in/", views.login_view , name="sign-in"),
    path("sign-out/", views.logout_view , name="sign-out"),
    path("forgot-password/", views.forgot_password_view , name="forgot-password"),
    path("reset-password/<str:uidb64>/<str:token>/", views.reset_password_view, name="reset-password"),
]

base/views.py
from heapq import merge
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
from django.http import JsonResponse
from django.core.mail import send_mail, EmailMultiAlternatives
from django.template.loader import render_to_string

import requests
import stripe

from base import models as base_models
from doctor import models as doctor_models
from patient import models as patient_models

# Create your views here.

def index(request):
    services = base_models.Service.objects.all()
    context = {
        "services":services
    }
    return render(request, "base/index.html", context)

def service_detail(request, service_id):
    service = base_models.Service.objects.get(id=service_id)
    context = {
        "service" : service
    }
    return render(request, "base/service_detail.html", context)


@login_required
def book_appointment(request, service_id, doctor_id):

    service = base_models.Service.objects.get(id=service_id)
    doctor = doctor_models.Doctor.objects.get(id=doctor_id)
    patient =  patient_models.Patient.objects.get(user=request.user)

    if request.method == "POST":
        first_name = request.POST.get("first_name")
        last_name = request.POST.get("last_name")
        email = request.POST.get("email")
        mobile = request.POST.get("mobile")
        gender = request.POST.get("gender")
        address = request.POST.get("address")
        dob = request.POST.get("dob")
        issues = request.POST.get("issues")
        symptoms = request.POST.get("symptoms")

        #Update Patient bio data
        patient.user.first_name = first_name
        patient.user.last_name = last_name
        patient.email = email
        patient.dob = dob
        patient.mobile = mobile
        patient.gender = gender
        patient.address = address
        patient.save()
        
        # Create appointement Object
        appointment = base_models.Appointment.objects.create (
            service = service,
            doctor = doctor,
            patient = patient,
            appointment_date = doctor.next_available_appointment_date,
            issues = issues,
            symptoms = symptoms,
        )

        billing = base_models.Billing()
        billing.patient = patient
        billing.appointment = appointment
        billing.sub_total = appointment.service.cost
        billing.tax = appointment.service.cost * 5 / 100
        billing.total = billing.sub_total + billing.tax
        billing.status = "Unpaid"
        billing.save()
        
        return redirect("base:checkout", billing.billing_id)

    context = {
        "service":service,
        "doctor":doctor,
        "patient":patient,
    }

    return render(request, "base/book_appointment.html", context)

@login_required
def checkout(request, billing_id):
    billing = base_models.Billing.objects.get(billing_id=billing_id)


    context = {
        "billing":billing,
        "stripe_public_key": settings.STRIPE_PUBLIC_KEY,

        "paypal_client_id": settings.PAYPAL_CLIENT_ID,
    }

    return render(request, "base/checkout.html", context)

@csrf_exempt
def stripe_payment(request, billing_id):
    billing = base_models.Billing.objects.get(billing_id=billing_id)
    stripe.api_key = settings.STRIPE_SECRET_KEY

    checkout_session = stripe.checkout.Session.create(
        customer_email=billing.patient.email,
        payment_method_types=['card'],
        line_items=[{
                'price_data':{
                    'currency':'USD',
                    'product_data':
                        { 'name':billing.patient.full_name },
                    'unit_amount':int(billing.total) * 100
                },
                'quantity':1,
            }],
        mode='payment',
        success_url=request.build_absolute_uri(reverse("base:stripe_payment_verify", args=[billing.billing_id])) + "?session_id={CHECKOUT_SESSION_ID}",
        cancel_url=request.build_absolute_uri(reverse("base:stripe_payment_verify", args=[billing.billing_id])),

    )
    return JsonResponse({"sessionId": checkout_session.id})

def stripe_payment_verify(request, billing_id):
    billing = base_models.Billing.objects.get(billing_id=billing_id)
    session_id = request.GET.get("session_id")

    if not session_id:
        return redirect(f"/payment_status/{billing.billing_id}/?payment_status=failed")
    
    session = stripe.checkout.Session.retrieve(session_id)

    if session.payment_status == "paid":
        if billing.status == "Unpaid":
            billing.status = "Paid"
            billing.save()
            billing.appointment.status = "completed"
            billing.appointment.save()


            doctor_models.Notification.objects.create(
                doctor = billing.appointment.doctor,
                appointment = billing.appointment,
                type = "New Appointment"
            )

            patient_models.Notification.objects.create(
                doctor = billing.appointment.patient,
                appointment = billing.appointment,
                type = "Appointment Scheduled"
            )

            return redirect(f"/payment_status/{billing.billing_id}/?payment_status=paid")
        
        else:
            return redirect(f"/payment_status/{billing.billing_id}/?payment_status=already_paid")
    else:
        return redirect(f"/payment_status/{billing.billing_id}/?payment_status=failed")


def get_paypal_access_toke():
    token_url = "https://api.sandbox.paypal.com/v1/oauth2/token"
    data = { "grant_type": "client_credentials" }
    auth =  (settings.PAYPAL_CLIENT_ID, settings.PAYPAY_SECRET_ID)
    response = requests.post(token_url, data=data, auth=auth)

    if response.status_code == 200:
        print("Access token obtained successfully.")
        response_data = response.json()
        return response_data.get("access_token")
    else:
        raise Exception(f"Failed to obtain access token from PayPal. Status code: {response.status_code}")
    


def paypal_payment_verify(request, billing_id):
    billing = base_models.Billing.objects.get(billing_id=billing_id)
    access_token = get_paypal_access_toke()
    transaction_id = request.GET.get("transaction_id")
    paypal_api_url = f"https://api-m.sandbox.paypal.com/v2/checkout/orders/{transaction_id}"
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {get_paypal_access_toke()}"
    }

    response = requests.get(paypal_api_url, headers=headers)

    if response.status_code == 200:
        paypal_order_data = response.json()
        paypal_payment_status = paypal_order_data['status']

        if paypal_payment_status == "COMPLETED":
            if billing.status == "Unpaid":
                billing.status = "Paid"
                billing.save()
                billing.appointment.status = "completed"
                billing.appointment.save()

                doctor_models.Notification.objects.create(
                    doctor = billing.appointment.doctor,
                    appointment = billing.appointment,
                    type = "New Appointment"
                )

                patient_models.Notification.objects.create(
                    patient = billing.appointment.patient,
                    appointment = billing.appointment,
                    type = "Appointment Scheduled"
                )

                merge_data = {
                    "billing":billing,
                }

                #DOCTOR EMAIL
                subject = "New Appointment"
                text_body = render_to_string("email/new_appointment.txt", merge_data)
                html_body = render_to_string("email/new_appointment.html", merge_data)

                msg = EmailMultiAlternatives(
                    subject=subject,
                    body=text_body,
                    from_email=settings.DEFAULT_FROM_EMAIL,
                    to=[billing.appointment.doctor.user.email]
                )
                msg.attach_alternative(html_body, "text/html")
                msg.send()

                #PATIENT EMAIL APPOINTMENT SCHEDULED
                subject = "Appointment Scheduled"
                text_body = render_to_string("email/appointment_scheduled.txt", merge_data)
                html_body = render_to_string("email/appointment_scheduled.html", merge_data)

                msg = EmailMultiAlternatives(
                    subject=subject,
                    body=text_body,
                    from_email=settings.DEFAULT_FROM_EMAIL,
                    to=[billing.appointment.patient.email]
                )
                msg.attach_alternative(html_body, "text/html")
                msg.send()

                return redirect(f"/payment_status/{billing.billing_id}/?payment_status=paid")
        else:
            return redirect(f"/payment_status/{billing.billing_id}/?payment_status=already_paid")
    else:
        return redirect(f"/payment_status/{billing.billing_id}/?payment_status=failed")

    

@login_required
def payment_status(request, billing_id):
    billing = base_models.Billing.objects.get(billing_id=billing_id)
    payment_status = request.GET.get("payment_status")

    context = {
        "billing":billing,
        "payment_status":payment_status,
    }

    return render(request, "base/payment_status.html", context)

def about(request):
    return render(request, "base/about.html")

def contact(request):
    if request.method == "POST":
        name = request.POST.get('name')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        message = request.POST.get('message')
        
        # Send email to admin
        try:
            send_mail(
                f"New Contact Form Submission - {subject}",
                f"Name: {name}\nEmail: {email}\n\nMessage:\n{message}",

templates/partials/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Dr.Life</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" />
        <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" />
    </head>
    <body>
        <!-- Navigation Bar -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand fw-bold fs-3" href="/">Dr.Life</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                    
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <div class="mx-auto">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="/">Home</a>
                            </li>
                            
                            {% if user.is_authenticated and user.doctor %}
                            <li class="nav-item">
                                <a class="nav-link text-white" href="{% url 'doctor:dashboard' %}">Doctor Dashboard </a>
                            </li>
                            {% endif %}

                            {% if user.is_authenticated and user.patient %}
                            <li class="nav-item">
                                <a class="nav-link text-white" href="{% url 'patient:dashboard' %}">Patient Dashboard </a>
                            </li>
                            {% endif %}

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"> Services </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    {% for service in services %}
                                        <li><a class="dropdown-item" href="{% url 'base:service_detail' service.id %}">{{ service.name }}</a></li>
                                    {% endfor %}
                                </ul>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"> Pages </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" href="{% url 'base:about' %}">About Us</a></li>
                                    <li><a class="dropdown-item" href="{% url 'base:contact' %}">Contact Us</a></li>
                                    <li><a class="dropdown-item" href="{% url 'base:privacy_policy' %}">Privacy Policy</a></li>
                                    <li><a class="dropdown-item" href="{% url 'base:terms_conditions' %}">Terms & Conditions</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>

                    <div class="d-flex ms-auto">
                        {% if user.is_authenticated %}
                            <a href="{% url 'userauths:sign-out' %}" class="btn btn-danger me-2 rounded-pill" type="submit" > Logout <i class="fas fa-sign-out-alt"></i></a>
                        {% else %}
                            <a href="{% url 'userauths:sign-in' %}" class="btn bg-white me-2 rounded-pill" type="submit" >Login <i class="fas fa-sign-in-alt"></i></a>
                            <a href="{% url 'userauths:sign-up' %}" class="btn btn-primary rounded-pill" type="submit">Register <i class="fas fa-user-plus"></i></a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>

        {% for message in messages %}
            <div class = "alert alert-{{message.tags}} alert-dismissible fade show text-center " role = "alert"  >
                <strong> {{ message }} </strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="close" > </button> 
            </div>     
        {% endfor %}

        {% block content %}
            
        {% endblock content %}
            

        <!-- Footer Section -->
        <section class="container">
            <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
                <div class="col-md-4 d-flex align-items-center">
                    <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
                        <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap" /></svg>
                    </a>
                    <span class="mb-3 mb-md-0 text-muted">&copy; 2025 Dr.Life, Inc</span>
                </div>

                <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
                    <li class="ms-3 fs-3">
                        <a class="text-muted" href="#"><i class="fab fa-instagram"></i></a>
                    </li>
                    <li class="ms-3 fs-3">
                        <a class="text-muted" href="#"><i class="fab fa-twitter"></i></a>
                    </li>
                    <li class="ms-3 fs-3">
                        <a class="text-muted" href="#"><i class="fab fa-facebook"></i></a>
                    </li>
                </ul>
            </footer>
        </section>
        <script src="{% static 'assets/js/script.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    </body>
</html>