Drlife/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("base.urls")),
    path("auth/", include("userauths.urls")),
    path("patient/", include("patient.urls")),
    path("doctor/", include("doctor.urls")),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

base/urls.py
from django.urls import path
from base import views

app_name = "base"

urlpatterns = [
    path("", views.index, name="index"),
    path("service/<service_id>", views.service_detail, name="service_detail"),
    path("book-appointment/<service_id>/<doctor_id>/", views.book_appointment, name="book_appointment"),
    path("checkout/<billing_id>", views.checkout, name="checkout"),
    
    path("payment_status/<billing_id>/", views.payment_status, name="payment_status"),

    path("stripe_payment/<billing_id>/", views.stripe_payment, name="stripe_payment"),
    path("stripe_payment_verify/<billing_id>", views.stripe_payment_verify, name="stripe_payment_verify"),

    path("paypal_payment_verify/<billing_id>/", views.paypal_payment_verify, name="paypal_payment_verify"),

    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("privacy-policy/", views.privacy_policy, name="privacy_policy"),
    path("terms-conditions/", views.terms_conditions, name="terms_conditions"),
    path("services/", views.services, name="services"),
]

patient/urls.py
from django.urls import path
from patient import views

app_name = "patient"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("appointment/", views.appointment, name="appointment"),
    path("appointment/<int:appointment_id>", views.appointment_detail, name="appointment_detail"),

    path("cancel_appointment/<int:appointment_id>", views.cancel_appointment, name="cancel_appointment"),
    path("activate_appointment/<int:appointment_id>", views.activate_appointment, name="activate_appointment"),

    path("medical_report/<int:appointment_id>", views.medical_report, name="medical_report"),

    path("payments/", views.payments, name="payments"),
    path("notifications/", views.notifications, name="notifications"),
    path("seen_notification/<int:id>", views.seen_notification, name="seen_notification"),

    path("profile/", views.profile, name="profile"),

    path("prescription/<int:appointment_id>", views.prescription, name="prescription"),
    path("medical_report/<int:appointment_id>", views.medical_report, name="medical_report"),
]

userauths/urls.py
from django.urls import path

from userauths import views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.register_view , name="sign-up"),
    path("sign-in/", views.login_view , name="sign-in"),
    path("sign-out/", views.logout_view , name="sign-out"),
    path("forgot-password/", views.forgot_password_view , name="forgot-password"),
    path("reset-password/<str:uidb64>/<str:token>/", views.reset_password_view, name="reset-password"),
]

base/models.py
from django.db import models
from shortuuid.django_fields import ShortUUIDField

from doctor import models as doctor_models
from patient import models as patient_models

# Create your models here.
class Service(models.Model):
    image = models.ImageField(upload_to="images", null=True, blank=True)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    cost = models.DecimalField(max_digits=10, decimal_places=2)
    available_doctors = models.ManyToManyField(doctor_models.Doctor, blank=True)

    def __str__(self):
        return f"{self.name} - {self.cost}"
    
class Appointment(models.Model):
    STATUS = [
        ('Scheduled','Scheduled'),
        ('Completed','Completed'),
        ('Pending','Pending'),
        ('Cancelled','Cancelled'),
    ]

    service = models.ForeignKey(Service, on_delete=models.SET_NULL, null=True, blank=True, related_name='service_app')
    doctor = models.ForeignKey(doctor_models.Doctor, on_delete=models.SET_NULL, null=True, blank=True, related_name='service_app')
    patient = models.ForeignKey(patient_models.Patient, on_delete=models.SET_NULL, null=True, blank=True, related_name='service_app')
    appointment_date = models.DateTimeField(null=True, blank=True)
    issues = models.TextField(blank=True, null=True)
    symptoms = models.TextField(blank=True, null=True)
    appointment_id = ShortUUIDField(length=6, max_length=10, alphabet="1234567890")
    status = models.CharField(max_length=120, choices=STATUS)

    def __str__(self):
        return f"{self.patient.user.first_name} {self.patient.user.last_name} with {self.doctor.user.first_name} {self.doctor.user.last_name}"
    

class MedicalRecord(models.Model):
    appointment = models.ForeignKey(Appointment, on_delete=models.CASCADE)
    diagnosis = models.TextField()
    treatment = models.TextField()

    def __str__(self):
        return f"Medical Record for {self.appointment.patient.user.first_name} {self.appointment.patient.user.last_name}"
    
class LabTest(models.Model):
    appointment = models.ForeignKey(Appointment, on_delete=models.CASCADE)
    test_name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    result = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.test_name}"
    
class Prescription(models.Model):
    appointment = models.ForeignKey(Appointment, on_delete=models.CASCADE)
    medications = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"Prescription for {self.appointment.patient.user.first_name} {self.appointment.patient.user.last_name}"
    
class Billing(models.Model):
    patient = models.ForeignKey(patient_models.Patient, on_delete=models.SET_NULL, null=True, blank=True, related_name="billing")
    appointment = models.ForeignKey(Appointment, on_delete=models.CASCADE, related_name='billing', blank=True, null=True)
    sub_total = models.DecimalField(max_digits=10, decimal_places=2)
    tax = models.DecimalField(max_digits=10, decimal_places=2)
    total = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(max_length=100, choices=[('Paid','Paid'),('Unpaid','Unpaid')])
    billing_id = ShortUUIDField(length=6, max_length=10, alphabet ='1234567890')

    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        patient_name = self.patient.user.last_name if self.patient else "Deleted Patient"
        return f"Billing for {patient_name} - Total: {self.total}"

base/views.py
from heapq import merge
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
from django.http import JsonResponse
from django.core.mail import send_mail, EmailMultiAlternatives
from django.template.loader import render_to_string

import requests
import stripe

from base import models as base_models
from doctor import models as doctor_models
from patient import models as patient_models

# Create your views here.

def index(request):
    services = base_models.Service.objects.all()
    context = {
        "services":services
    }
    return render(request, "base/index.html", context)

def service_detail(request, service_id):
    service = base_models.Service.objects.get(id=service_id)
    context = {
        "service" : service
    }
    return render(request, "base/service_detail.html", context)


@login_required
def book_appointment(request, service_id, doctor_id):

    service = base_models.Service.objects.get(id=service_id)
    doctor = doctor_models.Doctor.objects.get(id=doctor_id)
    patient =  patient_models.Patient.objects.get(user=request.user)

    if request.method == "POST":
        first_name = request.POST.get("first_name")
        last_name = request.POST.get("last_name")
        email = request.POST.get("email")
        mobile = request.POST.get("mobile")
        gender = request.POST.get("gender")
        address = request.POST.get("address")
        dob = request.POST.get("dob")
        issues = request.POST.get("issues")
        symptoms = request.POST.get("symptoms")

        #Update Patient bio data
        patient.user.first_name = first_name
        patient.user.last_name = last_name
        patient.email = email
        patient.dob = dob
        patient.mobile = mobile
        patient.gender = gender
        patient.address = address
        patient.save()
        
        # Create appointement Object
        appointment = base_models.Appointment.objects.create (
            service = service,
            doctor = doctor,
            patient = patient,
            appointment_date = doctor.next_available_appointment_date,
            issues = issues,
            symptoms = symptoms,
        )

        billing = base_models.Billing()
        billing.patient = patient
        billing.appointment = appointment
        billing.sub_total = appointment.service.cost
        billing.tax = appointment.service.cost * 5 / 100
        billing.total = billing.sub_total + billing.tax
        billing.status = "Unpaid"
        billing.save()
        
        return redirect("base:checkout", billing.billing_id)

    context = {
        "service":service,
        "doctor":doctor,
        "patient":patient,
    }

    return render(request, "base/book_appointment.html", context)

@login_required
def checkout(request, billing_id):
    billing = base_models.Billing.objects.get(billing_id=billing_id)


    context = {
        "billing":billing,
        "stripe_public_key": settings.STRIPE_PUBLIC_KEY,

        "paypal_client_id": settings.PAYPAL_CLIENT_ID,
    }

    return render(request, "base/checkout.html", context)

@csrf_exempt
def stripe_payment(request, billing_id):
    billing = base_models.Billing.objects.get(billing_id=billing_id)
    stripe.api_key = settings.STRIPE_SECRET_KEY

    checkout_session = stripe.checkout.Session.create(
        customer_email=billing.patient.email,
        payment_method_types=['card'],
        line_items=[{
                'price_data':{
                    'currency':'USD',
                    'product_data':
                        { 'name':billing.patient.full_name },
                    'unit_amount':int(billing.total) * 100
                },
                'quantity':1,
            }],
        mode='payment',
        success_url=request.build_absolute_uri(reverse("base:stripe_payment_verify", args=[billing.billing_id])) + "?session_id={CHECKOUT_SESSION_ID}",
        cancel_url=request.build_absolute_uri(reverse("base:stripe_payment_verify", args=[billing.billing_id])),

    )
    return JsonResponse({"sessionId": checkout_session.id})

def stripe_payment_verify(request, billing_id):
    billing = base_models.Billing.objects.get(billing_id=billing_id)
    session_id = request.GET.get("session_id")

    if not session_id:
        return redirect(f"/payment_status/{billing.billing_id}/?payment_status=failed")
    
    session = stripe.checkout.Session.retrieve(session_id)

    if session.payment_status == "paid":
        if billing.status == "Unpaid":
            billing.status = "Paid"
            billing.save()
            billing.appointment.status = "completed"
            billing.appointment.save()


            doctor_models.Notification.objects.create(
                doctor = billing.appointment.doctor,
                appointment = billing.appointment,
                type = "New Appointment"
            )

            patient_models.Notification.objects.create(
                doctor = billing.appointment.patient,
                appointment = billing.appointment,
                type = "Appointment Scheduled"
            )

            return redirect(f"/payment_status/{billing.billing_id}/?payment_status=paid")
        
        else:
            return redirect(f"/payment_status/{billing.billing_id}/?payment_status=already_paid")
    else:
        return redirect(f"/payment_status/{billing.billing_id}/?payment_status=failed")


def get_paypal_access_toke():
    token_url = "https://api.sandbox.paypal.com/v1/oauth2/token"
    data = { "grant_type": "client_credentials" }
    auth =  (settings.PAYPAL_CLIENT_ID, settings.PAYPAY_SECRET_ID)
    response = requests.post(token_url, data=data, auth=auth)

    if response.status_code == 200:
        print("Access token obtained successfully.")
        response_data = response.json()
        return response_data.get("access_token")
    else:
        raise Exception(f"Failed to obtain access token from PayPal. Status code: {response.status_code}")
    


def paypal_payment_verify(request, billing_id):
    billing = base_models.Billing.objects.get(billing_id=billing_id)
    access_token = get_paypal_access_toke()
    transaction_id = request.GET.get("transaction_id")
    paypal_api_url = f"https://api-m.sandbox.paypal.com/v2/checkout/orders/{transaction_id}"
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {get_paypal_access_toke()}"
    }

    response = requests.get(paypal_api_url, headers=headers)

    if response.status_code == 200:
        paypal_order_data = response.json()
        paypal_payment_status = paypal_order_data['status']

        if paypal_payment_status == "COMPLETED":
            if billing.status == "Unpaid":
                billing.status = "Paid"
                billing.save()
                billing.appointment.status = "completed"
                billing.appointment.save()

                doctor_models.Notification.objects.create(
                    doctor = billing.appointment.doctor,
                    appointment = billing.appointment,
                    type = "New Appointment"
                )

                patient_models.Notification.objects.create(
                    patient = billing.appointment.patient,
                    appointment = billing.appointment,
                    type = "Appointment Scheduled"
                )

                merge_data = {
                    "billing":billing,
                }

                #DOCTOR EMAIL
                subject = "New Appointment"
                text_body = render_to_string("email/new_appointment.txt", merge_data)
                html_body = render_to_string("email/new_appointment.html", merge_data)

                msg = EmailMultiAlternatives(
                    subject=subject,
                    body=text_body,
                    from_email=settings.DEFAULT_FROM_EMAIL,
                    to=[billing.appointment.doctor.user.email]
                )
                msg.attach_alternative(html_body, "text/html")
                msg.send()

                #PATIENT EMAIL APPOINTMENT SCHEDULED
                subject = "Appointment Scheduled"
                text_body = render_to_string("email/appointment_scheduled.txt", merge_data)
                html_body = render_to_string("email/appointment_scheduled.html", merge_data)

                msg = EmailMultiAlternatives(
                    subject=subject,
                    body=text_body,
                    from_email=settings.DEFAULT_FROM_EMAIL,
                    to=[billing.appointment.patient.email]
                )
                msg.attach_alternative(html_body, "text/html")
                msg.send()

                return redirect(f"/payment_status/{billing.billing_id}/?payment_status=paid")
        else:
            return redirect(f"/payment_status/{billing.billing_id}/?payment_status=already_paid")
    else:
        return redirect(f"/payment_status/{billing.billing_id}/?payment_status=failed")

    

@login_required
def payment_status(request, billing_id):
    billing = base_models.Billing.objects.get(billing_id=billing_id)
    payment_status = request.GET.get("payment_status")

    context = {
        "billing":billing,
        "payment_status":payment_status,
    }

    return render(request, "base/payment_status.html", context)

def about(request):
    return render(request, "base/about.html")

def contact(request):
    if request.method == "POST":
        name = request.POST.get('name')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        message = request.POST.get('message')
        
        # Send email to admin
        try:
            send_mail(
                f"New Contact Form Submission - {subject}",
                f"Name: {name}\nEmail: {email}\n\nMessage:\n{message}",

templates/base/index.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}

            <!-- Hero Section -->
        <img src="{% static 'images/hero-bg.jpeg' %}" alt="Hero Background" class="position-absolute object-fit-cover rounded-bottom-4" width="100%" height="70%">
        <section class=" position-relative">
            <div class="container">
                <div class="row d-flex justify-content-end align-items-center">
                    <div class="col-12 col-lg-7 p-4 rounded-4 position-relative" style="background-color: rgba(255, 255, 255, 0.5);">
                        <h1 class="display-4 fw-bold mt-5 ">
                                Your Health Journey Starts With 
                                <span class="text-primary position-relative">
                                    Expert Care
                                    <svg class="position-absolute start-0 bottom-0" width="100%" height="10">
                                        <path d="M0,5 Q50,0 100,5" stroke="var(--bs-primary)" fill="none" stroke-width="2"/>
                                    </svg>
                                </span>
                            </h1>
                        <p class=" position-relative fs-5 mt-4 text-darker">We prioritize your wellbeing with state-of-the-art facilities, experienced doctors, and personalized care plans tailored just for you.</p>
                        <div class="d-flex align-items-center gap-4 mt-5"></div>
                    </div>
                    <div class="d-flex align-items-center gap-4 mt-5">
                        {% if user.is_authenticated %}
                        <a href="" class="btn btn-outline-primary btn-lg rounded-pill">Book Appointment <i class="fas fa-arrow-right ms-2"></i></a>
                        {% else %}
                        <a href="auth/sign-up/" class="btn btn-primary btn-lg rounded-pill">Create Account <i class="fas fa-user-plus ms-1"></i></a>
                        <a href="auth/sign-in/" class="btn btn-outline-primary btn-lg rounded-pill">Book Appointment <i class="fas fa-arrow-right ms-2"></i></a>
                        {% endif %}
                    </div>
                </div>
                <div class="col-12 col-lg-5">

                     <div class="position-absolute end-0 bg-white p-4 rounded-4 shadow-lg m-4 bg-opacity-50">
                        <div class="d-flex align-items-center gap-3">
                        <div class="rounded-circle bg-primary-subtle p-3">
                            <i class="fas fa-heartbeat text-primary fs-4"></i>
                        </div>
                        <div>
                            <h6 class="mb-1">Emergency Care</h6>
                            <p class="mb-0 text-muted small">24/7 Available</p>
                        </div>
                    </div>
                    </div>   

                </div>
            </div>
        </section>
        <!-- Service Section -->
        <section class="container mt-5">
            <div class="py-4">
                <h2 class="">Our Services</h2>
                <p class="text-darker mb-4 fs-5">
                    Discover our comprehensive healthcare solutions delivered by expert medical professionals. 
                    From routine check-ups to specialized treatments, we're committed to providing exceptional 
                    care that puts your health and comfort first.
                </p>
            </div>
            <div class="row">
                {% for s in services %}
                    <div class="col-lg-3">
                        <div class="card mb-4 shadow">
                            <a href="{% url 'base:service_detail' s.id %}">
                            <img src="{{s.image.url}}" alt="course" class="card-img-top" /></a>
                            <div class="card-body">
                                <h4 class="mb-2 text-truncate-line-2"><a href="{% url 'base:service_detail' s.id %}" class="text-inherit text-dark text-decoration-none"> {{s.name}} </a></h4>
                                <p> {{s.description|truncatechars:80}} </p>
                                <div class="mt-2">
                                    <span class="fw-semibold">Doctors Available: {{s.available_doctors.all.count}}</span>
                                    <div class="lh-1 mt-3">
                                        <span class="text-dark fw-bold fs-4"> {{s.cost}} </span></div>
                                    <a href="{% url 'base:service_detail' s.id %}" class="btn btn-sm btn-primary mt-3 rounded-pill">Book Appointment <i class="fas fa-arrow-right ms-2"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                </div>
            </div>
        </section>
        <!-- Appointment Section -->
        <section class="container mt-5">
            <div class="row d-flex align-items-center">
                <div class="col-lg-6">
                    <h1 class="fw-bold">Get Appointment Now!</h1>
                    <p class="text-darker fs-5">Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus et voluptate omnis accusantium. Tenetur explicabo vero quo dolore. Repudiandae itaque accusantium dolor ab. Blanditiis esse tempore ut ad accusantium nihil?</p>

                    <div class="d-flex align-items-center gap-2 mt-5">
                        {% if user.is_authenticated %}
                        <a href="{% url 'base:services' %}" class="btn btn-outline-primary rounded-pill"><i class="fas fa-video ms-1"></i> View Services</a>
                        <a href="{% url 'base:about' %}" class="btn btn-primary rounded-pill">Learn More <i class="fas fa-arrow-right ms-1"></i></a>
                        {% else %}
                        <a href="{% url 'base:services' %}" class="btn btn-outline-primary rounded-pill"><i class="fas fa-video ms-1"></i> View Services</a>
                        <a href="{% url 'userauths:sign-up' %}" class="btn btn-primary rounded-pill">Create Account <i class="fas fa-user-plus ms-1"></i></a>
                        <a href="{% url 'base:about' %}" class="btn btn-primary rounded-pill">Learn More <i class="fas fa-arrow-right ms-1"></i></a>
                        {% endif %}
                    </div>
                </div>
                <div class="col-lg-6">
                    <img src="https://www.mckenzielake.com/wp-content/uploads/2022/06/iStock-1299777111.jpg" class="img-fluid rounded" style="height: 400px" alt="" />
                </div>
            </div>
        </section>
    
{% endblock content %}
    

templates/base/payment_status.html
{% extends 'partials/base.html' %}


{% block content %}
<section class="container">
    <div class="container">
        {% if payment_status == "paid" %}
            <hr class="my-5" />
            <div class="d-flex justify-content-center flex-column align-items-center mb-5">
                <i class="fas fa-check-circle text-success display-1"></i>
                <h1>Appointment Scheduled Successfully</h1>
                <p class="text-success">Thanks for boking an appointment <i class="fas fa-check-circle"></i></p>
                <a href="{% url 'patient:dashboard' %}" class="btn btn-success d-flex align-items-center">My Dashboard <i class="bi bi-grid-fill ms-2"></i></a>
            </div>
        {% endif %}
        
        {% if payment_status == "already_paid" %} <!-- Need Spaces around the equal sign -->
        <hr class="my-5" />
        <div class="d-flex justify-content-center flex-column align-items-center mb-5">
            <i class="fas fa-spinner fa-spin text-warning display-1"></i>
            <h1>Appointment Scheduled Pending</h1>
            <p>We are processing your payment and enrollment, please hold on.</p>
        </div>

        {% endif %}
        
        {% if payment_status == "failed" %}
            <hr class="my-5" />
            <div class="d-flex justify-content-center flex-column align-items-center mb-5">
                <i class="fas fa-exclamation-triangle fa-flip text-danger display-1"></i>
                <h1>Appointment Scheduled Failed</h1>
                <p>We couldn't process your payment, please try again later. Thank you</p>
            </div>
        {% endif %}
    </div>
</section>    
{% endblock content %}
    

templates/base/privacy_policy.html
{% extends 'partials/base.html' %}
{% block content %}

{% endblock %}

templates/base/service_detail.html
{% extends 'partials/base.html' %}


{% block content %}

        <section class="container">
            <div class="row d-flex justify-content-center align-items-center">
                <div class="col-12 col-lg-7 p-4 rounded-3 bg-white">
                    <h1 class="display-4 fw-bold mt-5">
                        <span class="text-primary"><b> {{service.name}} </b></span>
                    </h1>
                    <p class="fs-4 mt-4"> {{service.description}} </p>
                </div>
                <div class="col-12 col-lg-5">
                    <img class="img-fluid mt-4" style="width: 100%; height: 350px; object-fit: cover; border-radius: 10px" src="{{service.image.url}}" alt="" />
                </div>
            </div>
        </section>

        <section class="container">
            <div class="">
                <h2 class="">Available Doctors</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis, reiciendis.</p>
            </div>
            <div class="">
                
                {% for d in service.available_doctors.all %}
                        
                    <div class="p-1 mb-4 shadow d-flex align-items-center rounded-4">
                        <a href="course-detail.html">
                            <img src="{{d.image.url}}" alt="course" style="width: 70px; height: 70px; object-fit: cover; border-radius:10px" class="card-img-top ms-2" />
                        </a>
                        <div class="card-body">
                            <div class="ms-4 mt-2 d-flex justify-content-between align-items-center">
                                <div>
                                    <h5 class="mb-1 text-truncate-line-2"><a href="course-detail.html" class="text-inherit text-dark text-decoration-none">Dr. {{d.user.first_name}} {{d.user.last_name}}</a></h5>
                                    <div class="d-flex gap-2">
                                        <p class="fw-semibold mt-0 mb-0">Time Available:</p>
                                        <p class="mt-0 mb-0">{{d.next_available_appointment_date}}</p>
                                    </div>
                                    <div class="d-flex gap-2">
                                        <p class="fw-semibold mt-0 mb-0">Price:</p>
                                        <p class="mt-0 mb-0">${{service.cost}}</p>
                                    </div>
                                </div>

                                <div>
                                    <a href="{% url 'base:book_appointment' service.id d.id %}" class="btn btn-primary me-4 rounded-pill">Book Now <i class="fas fa-arrow-right ms-2"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                    

            </div>
        </section>



    
{% endblock content %}
    

templates/base/services.html
{% extends 'partials/base.html' %}
{% block content %}
<div class="row">
    {% for s in services %}
        <div class="col-lg-3 mt-5 ms-5">
            <div class="card mb-4 shadow">
                <a href="{% url 'base:service_detail' s.id %}">
                <img src="{{s.image.url}}" alt="course" class="card-img-top" /></a>
                <div class="card-body">
                    <h4 class="mb-2 text-truncate-line-2"><a href="{% url 'base:service_detail' s.id %}" class="text-inherit text-dark text-decoration-none"> {{s.name}} </a></h4>
                    <p> {{s.description|truncatechars:80}} </p>
                    <div class="mt-2">
                        <span class="fw-semibold">Doctors Available: {{s.available_doctors.all.count}}</span>
                        <div class="lh-1 mt-3">
                            <span class="text-dark fw-bold fs-4"> {{s.cost}} </span></div>
                        <a href="{% url 'base:service_detail' s.id %}" class="btn btn-sm btn-primary mt-3 rounded-pill">Book Appointment <i class="fas fa-arrow-right ms-2"></i></a>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
</div>

{% endblock content %}

templates/base/terms_conditions.html
{% extends 'partials/base.html' %}
{% block content %}

{% endblock %}