Drlife/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("base.urls")),
    path("auth/", include("userauths.urls")),
    path("patient/", include("patient.urls")),
    path("doctor/", include("doctor.urls")),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

base/urls.py
from django.urls import path
from base import views

app_name = "base"

urlpatterns = [
    path("", views.index, name="index"),
    path("service/<service_id>", views.service_detail, name="service_detail"),
    path("book-appointment/<service_id>/<doctor_id>/", views.book_appointment, name="book_appointment"),
    path("checkout/<billing_id>", views.checkout, name="checkout"),
    
    path("payment_status/<billing_id>/", views.payment_status, name="payment_status"),

    path("stripe_payment/<billing_id>/", views.stripe_payment, name="stripe_payment"),
    path("stripe_payment_verify/<billing_id>", views.stripe_payment_verify, name="stripe_payment_verify"),

    path("paypal_payment_verify/<billing_id>/", views.paypal_payment_verify, name="paypal_payment_verify"),

    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("privacy-policy/", views.privacy_policy, name="privacy_policy"),
    path("terms-conditions/", views.terms_conditions, name="terms_conditions"),
    path("services/", views.services, name="services"),
]

doctor/urls.py
from  django.urls import path
from doctor import views

app_name = 'doctor'

urlpatterns = [
    path("", views.dashboard, name='dashboard'),
    path("appointments/", views.appointments, name='appointments'),
    path("appointments/<appointment_id>/", views.appointment_detail, name='appointment_detail'),

    path("cancel_appointment/<appointment_id>/", views.cancel_appointment, name="cancel_appointment"),
    path("activate_appointment/<appointment_id>/", views.activate_appointment, name="activate_appointment"),
    path("complete_appointment/<appointment_id>/", views.complete_appointment, name="complete_appointment"),

    path("add_medical_report/<appointment_id>/", views.add_medical_report, name="add_medical_report"),
    path("edit_medical_report/<appointment_id>/<medical_report_id>/", views.edit_medical_report, name="edit_medical_report"),

    path("add_lab_test/<appointment_id>/", views.add_lab_test, name="add_lab_test"),
    path("edit_lab_test/<appointment_id>/<lab_test_id>/", views.edit_lab_test, name="edit_lab_test"),

    path("add_prescription/<appointment_id>/", views.add_prescription, name="add_prescription"),
    path("edit_prescription/<appointment_id>/<prescription_id>/", views.edit_prescription, name="edit_prescription"),

    path("payments/", views.payments, name="payments"),

    path("notifications/", views.notifications, name="notifications"),
    path("seen_notification/<id>/", views.seen_notification, name="seen_notification"),

    path("profile/", views.profile, name="profile"),

]

userauths/urls.py
from django.urls import path

from userauths import views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.register_view , name="sign-up"),
    path("sign-in/", views.login_view , name="sign-in"),
    path("sign-out/", views.logout_view , name="sign-out"),
    path("forgot-password/", views.forgot_password_view , name="forgot-password"),
    path("reset-password/<str:uidb64>/<str:token>/", views.reset_password_view, name="reset-password"),
]

doctor/models.py
from django.db import models
from django.utils import timezone

from userauths import models as userauths_models

NOTIFICATION_TYPE = (
    ("New Appointment","New Appointment"),
    ("Appointment Cancelled","Appointment Cancelled"),
)

# Create your models here.
class Doctor(models.Model):
    user = models.OneToOneField(userauths_models.User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="images", null=True, blank=True)
    country = models.CharField(max_length=100, null=True, blank=True)
    mobile = models.CharField(max_length=100, null=True, blank=True)
    bio = models.CharField(max_length=100, null=True, blank=True)
    specialization = models.CharField(max_length=100, null=True, blank=True)
    qualification = models.CharField(max_length=100, null=True, blank=True)
    years_experience = models.CharField(max_length=100, null=True, blank=True)
    next_available_appointment_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"Dr. {self.user.first_name} {self.user.last_name}"


class Notification(models.Model):
    doctor = models.ForeignKey(Doctor, on_delete=models.SET_NULL, null=True, blank=True)
    appointment = models.ForeignKey("base.Appointment", on_delete=models.CASCADE, null=True, blank=True , related_name="appointment_notification")
    type = models.CharField(max_length=100, choices=None)
    seen = models.BooleanField(default=False)
    date = models.DateTimeField(auto_now_add=True)  

    class Meta:
        verbose_name_plural = "Notification"

    def __str__(self):
        return f"Dr {self.doctor.user.first_name} {self.doctor.user.last_name} Notification"

doctor/views.py
from unittest import result
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from doctor import models as doctor_models
from base import models as base_models
import doctor

# Create your views here.

@login_required
def dashboard(request):
    doctor = doctor_models.Doctor.objects.get(user=request.user)
    appointments = base_models.Appointment.objects.filter(doctor=doctor).exclude(status='Completed').order_by('-appointment_date')
    notifications = doctor_models.Notification.objects.filter(doctor=doctor, seen=False)

    context  = {
        'appointments': appointments,
        'notifications': notifications,
        'unseen_notifications_count': notifications.count()
    }

    return render(request, 'doctor/dashboard.html', context)

@login_required
def appointments(request):
    doctor = doctor_models.Doctor.objects.get(user=request.user)
    appointments = base_models.Appointment.objects.filter(doctor=doctor)

    context  = {
        'appointments': appointments, 
    }

    return render(request, 'doctor/appointments.html', context)

@login_required
def appointment_detail(request, appointment_id):
    doctor = doctor_models.Doctor.objects.get(user=request.user)
    appointment = base_models.Appointment.objects.get(appointment_id=appointment_id, doctor=doctor)

    medical_records = base_models.MedicalRecord.objects.filter(appointment=appointment)
    lab_tests = base_models.LabTest.objects.filter(appointment=appointment)
    prescriptions = base_models.Prescription.objects.filter(appointment=appointment)

    context = {
        'appointment': appointment,
        'medical_records': medical_records,
        'lab_tests': lab_tests,
        'prescriptions': prescriptions,
    }

    return render(request, 'doctor/appointment_detail.html', context)

@login_required
def cancel_appointment(request, appointment_id):
    doctor = doctor_models.Doctor.objects.get(user=request.user)
    appointment = base_models.Appointment.objects.get(appointment_id=appointment_id, doctor=doctor)

    appointment.status = 'Cancelled'
    appointment.save()

    messages.success(request, 'Appointment cancelled successfully.')
    return redirect("doctor:appointment_detail", appointment.appointment_id)

@login_required
def activate_appointment(request, appointment_id):
    doctor = doctor_models.Doctor.objects.get(user=request.user)
    appointment = base_models.Appointment.objects.get(appointment_id=appointment_id, doctor=doctor)

    appointment.status = 'Scheduled'
    appointment.save()

    messages.success(request, 'Appointment Re-Scheduled successfully.')
    return redirect("doctor:appointment_detail", appointment.appointment_id)

@login_required
def complete_appointment(request, appointment_id):
    doctor = doctor_models.Doctor.objects.get(user=request.user)
    appointment = base_models.Appointment.objects.get(appointment_id=appointment_id, doctor=doctor)

    appointment.status = 'Completed'
    appointment.save()

    messages.success(request, 'Appointment Completed successfully.')
    return redirect("doctor:appointment_detail", appointment.appointment_id)

@login_required
def add_medical_report(request, appointment_id):
    doctor = doctor_models.Doctor.objects.get(user=request.user)
    appointment = base_models.Appointment.objects.get(appointment_id=appointment_id, doctor=doctor)

    if request.method == "POST":
        diagnosis = request.POST.get("diagnosis")
        treatment = request.POST.get("treatment")
        base_models.MedicalRecord.objects.create(appointment=appointment, diagnosis=diagnosis, treatment=treatment)

    messages.success(request, 'Medical Report Added .')
    return redirect("doctor:appointment_detail", appointment.appointment_id)

@login_required
def edit_medical_report(request, appointment_id, medical_report_id):
    doctor = doctor_models.Doctor.objects.get(user=request.user)
    appointment = base_models.Appointment.objects.get(appointment_id=appointment_id, doctor=doctor)
    medical_report = base_models.MedicalRecord.objects.get(id=medical_report_id, appointment=appointment)

    if request.method == "POST":
        diagnosis = request.POST.get("diagnosis")
        treatment = request.POST.get("treatment")

        medical_report.diagnosis = diagnosis
        medical_report.treatment = treatment
        medical_report.save()

    messages.success(request, 'Medical Report Updated Successfully .')
    return redirect("doctor:appointment_detail", appointment.appointment_id)

@login_required
def add_lab_test(request, appointment_id):
    doctor = doctor_models.Doctor.objects.get(user=request.user)
    appointment = base_models.Appointment.objects.get(appointment_id=appointment_id, doctor=doctor) 

    if request.method == "POST":
        test_name = request.POST.get("test_name")
        description = request.POST.get("description")
        result = request.POST.get("result")
        base_models.LabTest.objects.create(appointment=appointment, test_name=test_name, description=description, result=result)

    messages.success(request, 'Lab Report Added Successfully .')
    return redirect("doctor:appointment_detail", appointment.appointment_id)


@login_required
def edit_lab_test(request, appointment_id, lab_test_id):
    doctor = doctor_models.Doctor.objects.get(user=request.user)
    appointment = base_models.Appointment.objects.get(appointment_id=appointment_id, doctor=doctor) 
    lab_test = base_models.LabTest.objects.get(id=lab_test_id, appointment=appointment)

    if request.method == "POST":
        test_name = request.POST.get("test_name")
        description = request.POST.get("description")
        result = request.POST.get("result")

        lab_test.test_name = test_name
        lab_test.description = description
        lab_test.result = result
        lab_test.save()

    messages.success(request, 'Lab Report Updated Successfully .')
    return redirect("doctor:appointment_detail", appointment.appointment_id)

@login_required
def add_prescription(request, appointment_id):
    doctor = doctor_models.Doctor.objects.get(user=request.user)
    appointment = base_models.Appointment.objects.get(appointment_id=appointment_id, doctor=doctor)

    if request.method == "POST":
        medications = request.POST.get("medications")
        base_models.Prescription.objects.create(appointment=appointment, medications=medications)

    messages.success(request, 'Prescription Added Successfully .')
    return redirect("doctor:appointment_detail", appointment.appointment_id)

@login_required
def edit_prescription(request, appointment_id, prescription_id):
    doctor = doctor_models.Doctor.objects.get(user=request.user)
    appointment = base_models.Appointment.objects.get(appointment_id=appointment_id, doctor=doctor)
    prescription = base_models.Prescription.objects.get(id=prescription_id)

    if request.method == "POST":
        medications = request.POST.get("medications")
        prescription.medications = medications
        prescription.save()

    messages.success(request, 'Prescription Updated Successfully .')
    return redirect("doctor:appointment_detail", appointment.appointment_id)


@login_required
def payments(request):
    doctor = doctor_models.Doctor.objects.get(user=request.user)
    payments = base_models.Billing.objects.filter(
        appointment__doctor=doctor, 
        status="Paid"
    )

    context = {
        'payments': payments,
    }

    return render(request, 'doctor/payments.html', context)


@login_required
def notifications(request):
    doctor = doctor_models.Doctor.objects.get(user=request.user)
    notifications = doctor_models.Notification.objects.filter(doctor=doctor, seen=False)

    context = {
        'notifications': notifications,
    }

    return render(request, 'doctor/notifications.html', context)

@login_required
def seen_notification(request, id):
    doctor = doctor_models.Doctor.objects.get(user=request.user)
    notification = doctor_models.Notification.objects.get(doctor=doctor, id=id)
    notification.seen = True
    notification.save()

    messages.success(request, 'Notification Seen Successfully .')
    return redirect("doctor:notifications")

@login_required
def profile(request):
    doctor = doctor_models.Doctor.objects.get(user=request.user)
    formatted_next_available_appointment_date = doctor.next_available_appointment_date.strftime("%Y-%m-%d")
    
    if request.method == "POST":
        first_name = request.POST.get("first_name")
        last_name = request.POST.get("last_name")
        image = request.FILES.get("image")
        mobile = request.POST.get("mobile")
        address = request.POST.get("address")
        specialization = request.POST.get("specialization")
        qualification = request.POST.get("qualification")
        years_of_experience = request.POST.get("years_of_experience")
        next_available_appointment_date = request.POST.get("next_available_appointment_date")

        if image != None:
            doctor.image = image

        doctor.user.first_name = first_name
        doctor.user.last_name = last_name
        doctor.user.save()
        
        doctor.mobile = mobile
        doctor.address = address
        doctor.specialization = specialization
        doctor.qualification = qualification
        doctor.years_of_experience = years_of_experience
        doctor.next_available_appointment_date = next_available_appointment_date
        doctor.save()

        messages.success(request, 'Profile Updated Successfully .')
        return redirect("doctor:profile")

    context = {
        "doctor": doctor,
        "formatted_next_available_appointment_date": formatted_next_available_appointment_date,
    }

    return render(request, "doctor/profile.html", context)
        
    

templates/doctor/appointment_detail.html
{% extends "partials/base.html" %}


{% block content %}
<section class="pt-5 pb-5">
    <div class="container">
        <div class="row mt-0 mt-md-4">
            {% include 'doctor/sidebar.html' %}
            <div class="col-lg-9 col-md-8 col-12">
                <h4 class="mb-0 mb-4 fw-bold">Appointment Detail #{{appointment.appointment_id}}</h4>
                <div class="card mb-4">
                    <div class="shadow border p-3 mb-4 rounded-4">
                        <p>
                            <a>
                                <p><span class="fw-semibold text-dark">Appointment ID:</span> {{appointment.appointment_id}} </p>
                                <p><span class="fw-semibold text-dark">Service:</span> {{appointment.service.name}} </p>
                                <p><span class="fw-semibold text-dark">Patient:</span> {{appointment.patient.full_name}}</p>
                                <p><span class="fw-semibold text-dark">Issue:</span> {{appointment.issues}} </p>
                                <p><span class="fw-semibold text-dark">Symptoms:</span> {{appointment.symptoms}} </p>
                                <p><span class="fw-semibold text-dark">Status:</span> {{appointment.status}} </p>
                                <p><span class="fw-semibold text-dark">Date:</span> {{appointment.appointment_date}} </p>
                                <p>
                                    <span class="fw-semibold text-dark">Action:</span>
                                    
                                    {% if appointment.status == 'Scheduled' %}
                                        <a href="{% url 'doctor:cancel_appointment' appointment.appointment_id %}" class="btn btn-outline-danger btn-sm">Cancel Appointment <i class="fas fa-trash ms-2"></i></a>
                                        <a href="{% url 'doctor:complete_appointment' appointment.appointment_id  %}" class="btn btn-outline-success btn-sm">Complete Appointment <i class="fas fa-check-circle ms-2"></i></a>
                                    
                                    {% elif appointment.status == 'Cancelled' %}
                                        <a href="{% url 'doctor:activate_appointment' appointment.appointment_id  %}" class="btn btn-outline-success btn-sm">Activate Appointment <i class="fas fa-check-circle ms-2"></i></a>
                                    
                                    {% elif appointment.status == 'Completed' %}
                                        <a href="" class="btn btn-success btn-sm">Appointment Completed <i class="fas fa-check-circle ms-2"></i></a>

                                    {% elif appointment.status == '' %}
                                        <a href="" class="btn btn-outline-danger btn-sm"> ERROR : STATUS UNKNOWN <i class="fas fa-check-circle ms-2"></i></a>
                                        <a href="{% url 'doctor:activate_appointment' appointment.appointment_id  %}" class="btn btn-outline-success btn-sm">Activate Appointment <i class="fas fa-check-circle ms-2"></i></a>
                                    {% else %}
                                        <a href="" class="btn btn-outline-warning btn-sm"> ERROR : STATUS UNDEFINED <i class="fas fa-check-circle ms-2"></i></a>
                                        <a href="{% url 'doctor:activate_appointment' appointment.appointment_id  %}" class="btn btn-outline-success btn-sm">Activate Appointment <i class="fas fa-check-circle ms-2"></i></a>
                                    {% endif %}
                                    
                                </p>
                            </a>
                        </p>
                    </div>
                </div>

                <div id="medical-report">
                    <div class="d-flex justify-content-between">
                        <h4 class="mb-0 mb-4 fw-bold">Medical Reports</h4>
                        <button class="btn btn-primary btn-sm" type="button" data-bs-toggle="collapse" data-bs-target="#collapseMedicalReport" aria-expanded="false" aria-controls="collapseMedicalReport">Add Medical Report <i class="fas fa-plus ms-2"></i></button>
                    </div>
                    <div class="collapse" id="collapseMedicalReport">
                        <div class="border p-3 mb-4 rounded-4">
                            <form action="{% url 'doctor:add_medical_report' appointment.appointment_id %}" method="POST">
                                {% csrf_token %}
                                <input type="text" class="form-control mb-3" name="diagnosis" placeholder="Diagnosis" />
                                <input type="text" class="form-control mb-3" name="treatment" placeholder="Treatment" />
                                <button type="submit" class="btn btn-secondary btn-sm">Save <i class="fas fa-save ms-2"></i></button>
                            </form>
                        </div>
                    </div>

                    <div class="card mb-4">
                        <div class="border p-3 mb-4 rounded-4">

                            {% for m in medical_records %}

                                <div class="shadow p-3 rounded-4 mb-3">
                                    <p><span class="fw-semibold text-dark">Diagnosis:</span> {{m.diagnosis}} </p>
                                    <p><span class="fw-semibold text-dark">Treatment:</span> {{m.treatment}} </p>
                                    <button class="btn btn-dark btn-sm" type="button" data-bs-toggle="collapse" data-bs-target="#collapseMedicalRecord{{m.id}}" aria-expanded="false" aria-controls="collapseMedicalRecord{{m.id}}">Edit <i class="fas fa-edit ms-2"></i></button>
                                    <div class="collapse mt-3" id="collapseMedicalRecord{{m.id}}">
                                        <div class="border p-3 rounded-4">
                                            <form action="{% url 'doctor:edit_medical_report' appointment.appointment_id m.id %}" method="POST">
                                                {% csrf_token %}
                                                <input type="text" class="form-control mb-3" value="{{m.diagnosis}}" name="diagnosis" placeholder="Diagnosis" />
                                                <input type="text" class="form-control mb-3" value="{{m.treatment}}" name="treatment" placeholder="Treatment" />
                                                <button type="submit" class="btn btn-secondary btn-sm">Save Changes <i class="fas fa-save ms-2"></i></button>
                                            </form>
                                        </div>
                                    </div>
                                </div>

                            {% empty %}
                                <p>No medical records</p>
                            {% endfor %}
                            
                        </div>
                    </div>
                </div>

                <div id="lab-test">
                    <div class="d-flex justify-content-between">
                        <h4 class="mb-0 mb-4 fw-bold">Labs Tests Reports</h4>
                        <button class="btn btn-primary btn-sm" type="button" data-bs-toggle="collapse" data-bs-target="#collapseLabTest" aria-expanded="false" aria-controls="collapseLabTest">Add Lab Test <i class="fas fa-plus ms-2"></i></button>
                    </div>
                    <div class="collapse" id="collapseLabTest">
                        <div class="border p-3 mb-4 rounded-4">
                            <form action="{% url 'doctor:add_lab_test' appointment.appointment_id %}" method="POST">
                                {% csrf_token %}
                                <input type="text" class="form-control mb-3" name="test_name" placeholder="Test name" />
                                <input type="text" class="form-control mb-3" name="description" placeholder="Description" />
                                <textarea class="form-control mb-3" name="result" placeholder="Lab Result"></textarea>
                                <button type="submit" class="btn btn-secondary btn-sm">Save <i class="fas fa-save ms-2"></i></button>
                            </form>
                        </div>
                    </div>
                    <div class="card mb-4">
                        <div class="border p-3 mb-4 rounded-4">
                            
                            {% for l in lab_tests %}
                            <div class="shadow p-3 rounded-4 mb-3">
                                <p><span class="fw-semibold text-dark">Test Name:</span> {{l.test_name}}</p>
                                <p><span class="fw-semibold text-dark">Description:</span> {{l.description}}</p>
                                <p><span class="fw-semibold text-dark">Result:</span> {{l.result|default:"Not added yet"}}</p>
                                <button class="btn btn-dark btn-sm" type="button" data-bs-toggle="collapse" data-bs-target="#collapseLabTest{{l.id}}" aria-expanded="false" aria-controls="collapseLabTest{{l.id}}">Edit <i class="fas fa-edit ms-2"></i></button>
                                <div class="collapse mt-3" id="collapseLabTest{{l.id}}">
                                    <div class="border p-3 rounded-4">
                                        <form action="{% url 'doctor:edit_lab_test' appointment.appointment_id l.id %}" method="POST">
                                            {% csrf_token %}
                                            <input type="text" class="form-control mb-3" value="{{l.test_name}}" name="test_name" placeholder="Test name" />
                                            <input type="text" class="form-control mb-3" value="{{l.description}}" name="description" placeholder="Description" />
                                            <textarea class="form-control mb-3" name="result" placeholder="Lab Result">{{l.result}}</textarea>
                                            <button type="submit" class="btn btn-secondary btn-sm">Save Changes <i class="fas fa-save ms-2"></i></button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                            {% empty %}
                            <p>No lab tests</p>
                            {% endfor %}
                        </div>
                    </div>
                </div>

                <div class="d-flex justify-content-between">
                    <h4 class="mb-0 mb-4 fw-bold">Prescription</h4>
                    <button class="btn btn-primary btn-sm" type="button" data-bs-toggle="collapse" data-bs-target="#collapsePrescription" aria-expanded="false" aria-controls="collapsePrescription">Add Prescription <i class="fas fa-plus ms-2"></i></button>
                </div>
                <div class="collapse" id="collapsePrescription">
                    <div class="border p-3 mb-4 rounded-4">
                        <form action="{% url 'doctor:add_prescription' appointment.appointment_id %}" method="POST">
                            {% csrf_token %}
                            <textarea class="form-control mb-3" name="medications" placeholder="Medications"></textarea>
                            <button type="submit" class="btn btn-secondary btn-sm">Save <i class="fas fa-save ms-2"></i></button>
                        </form>
                    </div>
                </div>
                <div class="card mb-4">
                    <div class="border p-3 mb-4 rounded-4">
                        {% for p in prescriptions %}
                        <div class="shadow p-3 rounded-4 mb-3">
                            <p><span class="fw-semibold text-dark">Medications:</span> {{p.medications}}</p>
                            <button class="btn btn-dark btn-sm" type="button" data-bs-toggle="collapse" data-bs-target="#collapsePrescription{{p.id}}" aria-expanded="false" aria-controls="collapsePrescription{{p.id}}">Edit <i class="fas fa-edit ms-2"></i></button>
                            <div class="collapse mt-3" id="collapsePrescription{{p.id}}">
                                <div class="border p-3 rounded-4">
                                    <form action="{% url 'doctor:edit_prescription' appointment.appointment_id p.id %}" method="POST">
                                        {% csrf_token %}
                                        <input type="text" class="form-control mb-3" name="medications" value="{{p.medications}}" placeholder="Medications" />
                                        <button type="submit" class="btn btn-secondary btn-sm">Save Changes <i class="fas fa-save ms-2"></i></button>
                                    </form>
                                </div>
                            </div>
                        </div>
                        {% empty %}
                        <p>No prescriptions</p>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


    
{% endblock content %}
    

templates/doctor/sidebar.html
{% load static %}
<div class="col-lg-3 col-md-4 col-12">
                <nav class="navbar navbar-expand-md shadow mb-4 mb-lg-0 sidenav border rounded-4">
                    <a class="d-xl-none d-lg-none d-md-none text-inherit fw-bold text-decoration-none text-dark p-3" href="#"> Menu </a>
                    <button class="navbar-toggler d-md-none icon-shape icon-sm rounded bg-primary text-light m-3" type="button" data-bs-toggle="collapse" data-bs-target="#sidenav" aria-controls="sidenav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="bi bi-grid"></span>
                    </button>

                    <div class="collapse navbar-collapse p-3" id="sidenav">
                        <div class="navbar-nav flex-column">
                            <div class="d-flex align-items-center mb-3">
                                <img src="{% if request.user.doctor.image %}{{request.user.doctor.image.url}}{% else %}{% static 'media/photos/default.jpg' %}{% endif %}" alt="avatar" class="rounded-circle avatar-xl" style="width: 70px; height: 70px; object-fit: cover" />
                                <div class="ms-3">
                                    <h5 class="mb-0 fw-bold">Dr. {{request.user.doctor.user.first_name}} {{request.user.doctor.user.last_name}}</h5>
                                    <p class="mb-1 fs-6">Doctor ID: # {{request.user.doctor.id}}</p>
                                </div>
                            </div>
                            <ul class="list-unstyled ms-n2 mb-4">
                                <li class="nav-item">
                                    <a class="dropdown-item nav-link" href="{% url 'doctor:dashboard' %}"><i class="bi bi-grid-fill"></i> Dashboard</a>
                                </li>
                                <li class="nav-item">
                                    <a class="dropdown-item nav-link" href=" {% url 'doctor:appointments' %} "><i class="fas fa-calendar"></i> Appointment</a>
                                </li>

                                <li class="nav-item">
                                    <a class="dropdown-item nav-link" href="{% url 'doctor:payments' %}"><i class="fas fa-credit-card"></i> Payments</a>
                                </li>
                                <li class="nav-item">
                                    <a class="dropdown-item nav-link" href="{% url 'doctor:notifications' %}"><i class="fas fa-bell"></i> Notification</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'doctor:profile' %}"> <i class="fas fa-edit"></i> Edit Profile </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'userauths:sign-out' %}"> <i class="fas fa-sign-out-alt"></i> Sign Out </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
            </div>